[default]
GATEWAY_API='API_KEY'
GATEWAY_CRYP='CRYP_KEY'
PAYMENT_GATEWAY_URL='URL_GATEWAY'
SENDGRID_API_KEY='API_KEY'

[development]
DATABASE_URL="postgresql://user:pass@host/database"
API_MAIL_URL="https://testapi.com/"
ACCESS_TOKEN_EXPIRE_MINUTES=15

[testing]
DATABASE_URL="postgresql://user:pass@host/database"
API_MAIL_URL="https://testapi.com/"
ACCESS_TOKEN_EXPIRE_MINUTES=15
