[default]
FILE_UPLOAD_CLIENT="WASABI"
ENDPOINT_UPLOAD_CLIENT="https://cdn.com"
ENDPOINT_UPLOAD_REGION="us-west-2"
BUCKET_NAME="bucket_name"
AWS_ACCESS_KEY_ID="NOT_SECURE_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY="NOT_SECURE_SECREY_KEY"
FILE_UPLOAD_PATH="http://localhost:8001/static/images/"
DATABASE_URL="postgresql://postgres_user:pass@localhost/ecommerce"
DATABASE_URI="postgresql+asyncpg://postgres_user:pass@localhost/ecommerce"
BROKER_URL = "amqp://guest:guest@localhost:5672//"
FRONTEND_URL="https://localhost:3000"
ADMIN_URL="http://localhost:5173"
REDIS_URL="redis://:@localhost:6379"
REDIS_DB=0
SECRET_KEY="NOT_SECURE_SECRET_KEY"
CONFIRMATION_KEY="NOT_SECURE_CONFIRMATION_KEY"
LOG_LEVEL="DEBUG"
LOG_BACKTRACE=true
API_MAIL_URL ="http://localhost:7777"
ACCESS_TOKEN_EXPIRE_MINUTES=30
ALGORITHM = "HS256"
COMPANY="MY_COMPANY"
ENVIRONMENT="development"
ZIP_CODE_SOURCE ="47590000"
SENTRY_DSN = "SENTRY_DSN"
PAYMENT_GATEWAY = "STRIPE"
MERCADO_PAGO_ACCESS_TOKEN = "TEST-0f0f0f0f-0f0f-0f0f-0f0f-0f0f0f0f0f0f"
MERCADO_PAGO_PUBLIC_KEY = "TEST-0f0f0f0f-0f0f-0f0f-0f0f-0f0f0f0f0f0f"
FREIGHT_GATEWAY = "CORREIOS"
CORREIOSBR_API_URL = "https://api.correios.com.br"
CLIENT_API_TIMEOUT = 10


[testing]
DATABASE_URL="postgresql+psycopg://postgres_user:pass123@localhost/ecommerce-test"
DATABASE_URI="postgresql+psycopg://postgres_user:pass123@localhost/ecommerce-test"
API_MAIL_URL="https://testapi.com/"
ACCESS_TOKEN_EXPIRE_MINUTES=15
LOG_LEVEL="DEBUG"
LOG_BACKTRACE=true
